
jdk:
  - oraclejdk8
  - openjdk8

sudo: true    # Recurring problem in travis according to github
language: java

install: ./gradlew assemble

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: Unit test
      script: ./gradlew test && ./gradlew check
      
